### ISSUE TITLE
Open *.twitch.tv with SmartTwitchTV

### ISSUE THREAD

**Issue by Generator** [fgl27/SmartTwitchTV#1]
Add URL handling to open twitch.tv links with SmartTwitchTV.

Useful if the user send an URL from one device (smartphone/tablet) to other (AndroidTV)

**Comment by fgl27** [comment]
I don't really know how to do this.

I have no idea if I will try to learn it, probably not.

If you know how do it and send a PR.

**Comment by fgl27** [comment]
So do you know how to

> send an URL from one device (smartphone/tablet) to other (AndroidTV)

????

**Comment by Generator** [comment]
No, im not a developer.
Set label "need help", if someone see it maybe could help

**Comment by fgl27** [comment]
Is not a question of be a developer. Have you ever shared a link from one device with another?

I think you can't, not the way you wanna, you can only share a link or something related from a app with the same app or with a app that you know exactly what it listen for.

So for that is needed to make a new app that can receive a shared link and that app be able to find and share the link with the TV one.

But is to much work in the developer side and in the user side.

**Comment by Generator** [comment]
I think is this  
https://developer.android.com/studio/write/app-link-indexing  
https://developer.android.com/training/app-links/index.html

> I think you can't, not the way you wanna, you can only share a link or something related from a app with the same app or with a app that you know exactly what it listen for.  

If you send an Youtube URL, asks is want's to open with Youtube app or browser (or other youtube appp), same with Twitch if you have official Twitch app

**Comment by fgl27** [comment]
> If you send an Youtube URL, asks is want's to open with Youtube app or browser (or other youtube appp), same with Twitch if you have official Twitch app

What I have ask you?

> So back to the issue... Have you ever shared a link from one device with another?

Have you answer me? NO, if some one makes a question I recommend you to always answer.

What have you ask me...

> Useful if the user send an URL from one device (smartphone/tablet) to other (AndroidTV)

that is not related to 

> If you send an Youtube URL, asks is want's to open with Youtube app or browser (or other youtube appp), same with Twitch if you have official Twitch app

Way, because that is not open a link on another device a thing that doesn't exist, you can only open device to same device.

Yes you can open a youtube video from one device to a TV device but only directly from the youtube app it self to it self on another device that has cast options.

As you didn't answer my question I assume you can find a answer, if some day  this became possible show me how and re-open.

**Comment by Generator** [comment]
How the link is shared or not that's not related to the issue, only handle *.twitch.tv URLs , like any other app does.

**Comment by fgl27** [comment]
Pointless featuring who browser web sites on TV devices?
Plus is not what you ask on first post.

And for some reason youtube links works the same as on a phone on TV device using chrome, but twitch links don't at least on my TV it see the twitch app installed but will not open the link on it or give a option probably because is not implemented on the twitch tv app as is a pointless featuring no one browser on a TV device after all chrome is not even on the play store you have to side load it.

but any why you have point all the links that show the how to so go for it make it happen.

**Comment by Generator** [comment]
You can send a URL from one device or a computer to an Android device with third party apps (Ex: KDEConnect, Pushbullet, AirDroid etc...), this is useful if SmartTwitchTV is on a AndroidTV or Android TV Box.    

Also the URL can be on a message, Youtube channel or other app.
