### ISSUE TITLE
FFZ emotes not working.

### ISSUE THREAD

**Issue by hunter1749** [fgl27/SmartTwitchTV#109]
**Describe the bug**
FFZ emotes don't display, but other like BTTV do.

**To Reproduce**
Try to click on FFZ emotes button when typing in chat, but it says FFZ isn't on this channel.

**Expected behavior**
FFZ emotes should work like in a browser on computer.

**Additional context**
I saw someone else chat how they couldn't see FFZ emotes, perhaps it's somehow exclusive to xqc channel on this app.

**Comment by fgl27** [comment]
If the problem is on one channel the problem is on the channel.

Add far as I know that steamer changed name that must had caused a issue.

Xqcow works wqc doesn't

https://www.frankerfacez.com/channel/xqcow
https://www.frankerfacez.com/channel/xqc


Not an app problem but steamer and ffz problem

**Comment by hunter1749** [comment]
Oh ok, so he be should fixing it then right? Or is there something I can do?

**Comment by Js41637** [comment]
The issue is the app looks up FFZ emotes by their twitch name instead of their account id. 
This is an FFZ issue in that they are using the old account name for xqc so when it looks up `xqc` it finds no emotes but you can get arround this by using their account id instead of their name.

The extension on desktop makes a request like this;
https://api.frankerfacez.com/v1/room/id/71092938

This app is doing;
https://api.frankerfacez.com/v1/room/xqc

**Comment by hunter1749** [comment]
Alright, thanks.
