### ISSUE TITLE
access tokens

### ISSUE THREAD

**Issue by dbfmuk** [fgl27/SmartTwitchTV#12]
Hi,

Noticed in the code you are using 'client_secret' as part of getting an app access token. This should not be used client side. Only server to server side. It should never be publicly revealed

https://github.com/fgl27/SmartTwitchTV/blob/master/apk/app/src/main/java/com/fgl27/twitch/Tools.java

also the client secret can seen in the following:
https://github.com/fgl27/SmartTwitchTV/blob/master/app/specific/AddCode.js
https://github.com/fgl27/SmartTwitchTV/blob/master/release/githubio/js/master_uncompressed.js
https://github.com/fgl27/SmartTwitchTV/blob/master/release/githubio/js/master.js

Please see:
https://dev.twitch.tv/docs/authentication/#registration

**Comment by fgl27** [comment]
I know how things work, do I have a server?
I'm a single developer I don't have funds to properly have that.

How do you think I can fix this?

explain???

**Comment by dbfmuk** [comment]
please see: https://dev.twitch.tv/docs/authentication/getting-tokens-oauth

**Comment by fgl27** [comment]
are yo joking?

You come here full things that no one cares only you, you can just [search for `client_secret` on github](https://github.com/search?q=client_secret&type=Code) to find hundreds of those codes and why? because is not a problem, I ask you a question and you replay with a link that you don't even know what is, if I made this app I know what is on that.

so do you even know what you are toking about? why do you care? are you going to help me or not?

if you don't have a proper answer just close this Because if you aren't helping I don't care for what you have

**Comment by fgl27** [comment]
You didn't properly made a conversation with me as you didn't replay to any of my question, you didn't help the project in any form or way I can only assume the reason you started this was to expose the project and have it harmed some how.

I keep this project up because the harmed of users that it has, if you wold harmed the project you wold not harm me but the user base and because of that I need to protect the project and it users I hope you receive a email with this message and on the future you don't try to harmed others that didn't do anything bad to you.
