### ISSUE TITLE
Bug: Cannot log in to get authorization key - Browser not supported

### ISSUE THREAD

**Issue by JamesSi22** [fgl27/SmartTwitchTV#130]
When trying to log in to Twitch to get the authorization key, it says that the browser is not supported. I can enter my user name and password, but when clicking submit, I get this message.

**Comment by JamesSi22** [comment]
Must have been a one off. Working now!

**Comment by fgl27** [comment]
This is a random bug introduced by twitch, it seems to has started this year.

They support page:

https://help.twitch.tv/s/article/supported-browsers?language=en_US#:~:text=Issues%20with%20Supported%20Browsers&text=Ensure%20your%20browser%20version%20is,Clear%20your%20cache%20and%20cookies.

Random as will show on a device for no reason and then will no longer.

In order to understand this anyone that has the issue needs to share the About of the app.

The app ‘about’ shows the app and browser version of the device plus some other information that is relative to understand this issue.
