### ISSUE TITLE
Remember time stamp on different devices

### ISSUE THREAD

**Issue by Sonia-js** [fgl27/SmartTwitchTV#133]
I have this app on two tvs in my house. One in the lounge and the other in the bedroom. When watching vods the app only remembers last watched on one tv. For example, if I am watching a vod on the lounge tv, the bedroom tv doesn’t remember the time stamp of where I last watched in the lounge and I have to fast forward to where I last watched on the other tv. It only remembers last watched on the tv you are currently viewing. Hope that makes sense? I am logged in on both tvs under the same account. 

By the way, this is a great app and I thank you for all the hard work you put into developing this. This app is well above the offical twitch app and actually works!

**Comment by fgl27** [comment]
The app history is an “in app thing”, third party apps don’t have access to most Twitch features that include history.

So I created an offline history.

In order to provide such a feature I would need access to the twitch service or a similar service, as I don’t have access to anything that is free I can't make it.

So unless someone provides a proper solution to synchronize history across devices I will not bother, you know open source app means anyone can help.

**Comment by Sonia-js** [comment]
Ok no problem. Just thought I would ask 😄 both tvs I use a foxtel now box which the app is downloaded from the google play store. Foxtel is the biggest streaming service here in Australia. Thanks for the quick reply and totally understand if it is not possible. 

![CAACA587-4203-418D-B643-A4F72D245F51](https://user-images.githubusercontent.com/123785838/215295939-c8c6c444-e7e3-4e57-8d0d-d6a837dc8d31.jpeg)
