### ISSUE TITLE
Ads with twitch turbom

### ISSUE THREAD

**Issue by thro86** [fgl27/SmartTwitchTV#165]
Device: Nvidia Shield 

Just started randomly getting occasional ad even though I have twitch turbo. Two ads in 1 hour. Never had this issue before. Not sure if this is an issue with SmartTwitchTV app so figured I would post here to ask.

This is not happening on desktop when viewing from the computer.

I tried logging out and logging back into the app, confirmed my turbo subscription is active. Not sure what else to try.

**Comment by Ur3rdIMcFly** [comment]
I have started having this same issue today on my Smart TV.

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/128

https://github.com/fgl27/SmartTwitchTV/issues/158

noting changed twitch thing

**Comment by fgl27** [comment]
https://github.com/fgl27/SmartTwitchTV/issues/172

**Comment by loudbacon** [comment]
so basically you are saying your application is broken, and you have no idea how to fix the bug/issue ? am i right in this.....its not a matter of understanding the application you made better. its a sudden change where now my turbo subscription is not registering within your app. which never happened until a week ago today.

**Comment by stevensmedia** [comment]
I think it's more that Twitch's service is growing ever more hostile to apps like this.

**Comment by fgl27** [comment]
> so basically you are saying your application is broken, and you have no idea how to fix the bug/issue ? am i right in this.....its not a matter of understanding the application you made better. its a sudden change where now my turbo subscription is not registering within your app. which never happened until a week ago today.

no that isn't the question, The question is that you can't see that you were lucky by to not having ads, was just a random case.

the app never gave you support for your turbo sub or any stream related privilege, See this image from one year ago

https://github.com/fgl27/SmartTwitchTV/blob/master/screenshot/logging.png

![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/53005cdc-1512-4e7e-ae4d-f79a637c2160)

does there say anything about your turbo access?

stop being stubborn, nothing changed in the app, nothing is broken the app is working as intended.

see this issue from 2021, so how this can be an issue of just a few days ago?

https://github.com/fgl27/SmartTwitchTV/issues/158

This is nothing new, you are just being stubborn, now that you are affected you are demanding a fix as if there is one.

in reality, what you are doing is very simply annoying me and because of users like you, I lost all will to do anything about it.

just go and use your turbo or wherever on the official app and be happy, give as much money as you can to twitch as that will make they never give you anything better, as that just ensures them that you are OK with their service, you give money don't complain and keep paying, so you are heapy so use they app and service and go away!

heapy now did you get an answer?

can you see how stupid you look writing these things here?
