### ISSUE TITLE
Ads since September 1.

### ISSUE THREAD

**Issue by lextra2** [fgl27/SmartTwitchTV#169]
Ads are passing through since the first of September.
I never got ads before and I've watched many streams for hundreds of hours.
And don't act like your app doesn't block ads, it totally did, until yesterday.

Also, don't bother linking a closed issue about the same problem. I just clicked through 10 different reports and you kept going, but none of these had a solution. Why would you even link them?!

**Comment by cloppeh** [comment]
Twitch changed something in the past 2 days to change the HLS video playlist on the back end. this app was not blocking ads just getting the direct video feed and bypassing the advertisement video. Streamlink does something similar and has the same problem. Give it a few days and someone will have a workaround. Right now the best is to buy turbo and watch on the official site or app.

the issues closed were because people mentioned they are turbo users. 3rd party apps are not allowed to read api for subscriptions and turbo.

**Comment by fgl27** [comment]
> Right now the best is to buy turbo and watch on the official site or app for an ad free experience.

That is it
