### ISSUE TITLE
Follow/Unfollow button not working

### ISSUE THREAD

**Issue by missiah** [fgl27/SmartTwitchTV#76]
While watching a Stream the button to Follow/Unfollow does not work, I have tried multiple times fully remove the User, add it again including Key but the problem stays the same.

When i press enter on Follow/Unfollow nothing happen.

https://i.imgur.com/slooPqD.jpg
https://i.imgur.com/FB7LiwO.jpg
 
 **Device:**
 - Fire TV Stick Gen.3
 - Fire OS 7.2.4.9

 **App:**
 - Apk 3.0.327
 - Web August 10 2021

**Comment by fgl27** [comment]
Twitch closed the access to the api

https://discuss.dev.twitch.tv/t/deprecation-of-create-and-delete-follows-api-endpoints/32351

**Comment by missiah** [comment]
Oh i see

**Comment by fgl27** [comment]
let it open

**Comment by fgl27** [comment]
If someday this is possible to add back I will.

**Comment by 1992ff** [comment]
Hi fgl,
I just found your project today and it is worlds apart from the official application. Very good work. With regards to the follow function, I read that because of limitations the API won't allow it anymore.

Any chance that it would be possible to store a list of followed creators locally? I don't know if you know the SkyTube project, but it is to YouTube, what your project is to Twitch. They have implemented an option to subscribe to channels without a signed in YouTube account, by creating the database of followed channels locally on your device. I would really appreciate it, if you consider trying to add a similar function in the future.

Thank you for your great work! Have a nice weekend!

**Comment by fgl27** [comment]
> Hi fgl, I just found your project today and it is worlds apart from the official application. Very good work. With regards to the follow function, I read that because of limitations the API won't allow it anymore.
> 
> Any chance that it would be possible to store a list of followed creators locally? I don't know if you know the SkyTube project, but it is to YouTube, what your project is to Twitch. They have implemented an option to subscribe to channels without a signed in YouTube account, by creating the database of followed channels locally on your device. I would really appreciate it, if you consider trying to add a similar function in the future.
> 
> Thank you for your great work! Have a nice weekend!

I have added that feature to the app TODO list already

https://github.com/fgl27/SmartTwitchTV/blob/master/apk/TODO.md#featured-request-list

It was requested via issue/feature request.

I don't plan to work on it anytime soon due to the complexity, but as this is an open-source app anyone can.

Thank you!

**Comment by RikuXan** [comment]
Just a short notice that following/unfollowing should work again. With the recent changes to allow the use of Twitch Turbo and subscriptions, adding in first-party API access made the feature work again.

**Comment by fgl27** [comment]
> If someday this is possible to add back I will.

Only took you years

![image](https://github.com/fgl27/SmartTwitchTV/assets/13755892/089f35e1-ab6e-4f09-9467-88e43b5edddc)

:grin: :satisfied: :joy:

In this pace I will be able to finish all Todo list in this millennium.
