### ISSUE TITLE
Feature request - Adjustable delay on host/raid

### ISSUE THREAD

**Issue by Kline-** [fgl27/SmartTwitchTV#89]
**Please describe the feature.**
Please consider adding either the option to select no delay or an adjustable delay for how quickly the video stream should change to a new channel if the current channel hosts or raids someone else.

**Additional context or samples**
Current behavior: I'm watching a channel who ends stream and hosts/raids to send viewers elsewhere. I receive the pop-up notification that the chat hosting has changed almost immediately, but the video stream stays on my original channel until the playback buffer runs out. I then see one pop-up notification that the player is lagging and it replays the last 10-15s of video buffer again before switching to the new channel's video stream.

Desired behavior: I'm watching a channel who ends stream and hosts/raids to send viewers elsewhere. I receive the pop-up notification that the chat hosting has changed and the video stream switches then as well, or after some delay I've configured in the settings.

**Comment by fgl27** [comment]
There is a no delay option, just enable the setting option from below image

![Screenshot_2021-12-18-13-00-20-81](https://user-images.githubusercontent.com/13755892/146647593-28ecfce1-e2fc-4d72-abe3-a862e306229d.jpg)

Twitch is very bugged because of that this feature isn't perfect, sometimes the stream will loop like that at the end because twitch servers doesn't send a end call... 

If you have the "always open the host" enabled and if the chat receives the host warning there player can switch before the loop... But isn't perfect as sometimes twitch send the warning without proper info just a name preventing the switch...

Like a wrote twitch is bugy the third party support is very limited because of that something are perfect.

**Comment by Kline-** [comment]
Looks like I do have the always open option turned on, I didn't realize it was (as usual) a twitch issue causing the delay, thanks for explaining!
